#!/bin/bash

echo -e "Install lxdrfile..."
wget ftp://ftp.gromacs.org/pub/contrib/xdrfile-1.1.1.tar.gz
tar xvzf xdrfile-1.1.1.tar.gz
cd xdrfile-1.1.1
./configure --enable-shared --prefix=/home/travis/xdrfile
make
make install
cd ..
echo -e "complete.\n"
